server:
  port: 8089
spring:
  application:
    name: order-service
  datasource: #数据库
    url: jdbc:mysql://localhost:3306/yun6?serverTimezone=UTC
    username: root
    password: luozhong168168
  jackson:
    default-property-inclusion: non_null #不允许结果是null的返回，也就是不显示null的值
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true
mybatis:
  type-aliases-package: com.leyou.order.pojo
ly:
  jwt:
    pubKeyPath: C:/dlion/rsa/rsa.pub # 公钥地址
    cookieName: LY_TOKEN