server:
  port: 8089
spring:
  application:
    name: order-service
  datasource: #数据库
    url: jdbc:mysql://localhost:3306/yun6?serverTimezone=UTC
    username: root
    password: luozhong168168
  jackson:
    default-property-inclusion: non_null #不允许结果是null的返回，也就是不显示null的值
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true
mybatis:
  type-aliases-package: com.leyou.order.pojo
ly:
  jwt:
    pubKeyPath: C:/dlion/rsa/rsa.pub # 公钥地址
    cookieName: LY_TOKEN
  worker: #雪花算法所需要的自定义id
    workerId: 1
    dataCenterId: 1
  pay:
    appId: wx8397f8696b538317
    mchId: 1473426802
    key: T6m9iK73b0kn9g5v426MKfHQH7X8rKwb
    connectTimeoutMs: 5000
    readTimeoutMs: 10000
    notifyUrl: http://h7rmfa.natappfree.cc/wxpay/notify #这里因为没有外网地址，所以本机设置了个内网穿透。