server:
  port: 10010
spring:
  application:
    name: api-gateway
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
zuul:
  prefix: /api #添加路由前缀
  routes:
    item-service: /item/** #将商品微服务映射到/item/**
    #设置upload的映射路径，禁止忽略路由前缀strip-prefix: false，不加item的直接localhost:10010/api/upload/image，后面还需要在前面添加/zuul
    #/zuul作用时虽然经过网关，但不用去缓存上传文件，减轻压力。可在Nginx配置rewrite，但这里直接在浏览器前加 localhost:10010/zuul/api/load/image
    upload-service:
      path: /upload/**
      serviceId: upload-service
      strip-prefix: false
    search-service: /search/** #讲搜索微服务映射到/search/**
    user-service: /user/** #讲搜索微服务映射到/user/**
    auth-service: /auth/** # 授权中心微服务
    cart-service: /cart/** #购物车微服务
    order-service: /order/** #订单微服务
  add-host-header: true #添加host头信息
  sensitive-headers: #放行所有敏感头 不填写即可。
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000 #熔断超时时长：5000ms
ribbon:
  ConnectTimeout: 1000 #ribbon链接超时时长
  ReadTimeout: 3500 #ribbon读取超时时长
  MaxAutoRetries: 0 #当前服务重试次数
  MaxAutoRetriesNextServer: 0 #切换服务重试次数
ly:
  jwt:
    pubKeyPath: C:/dlion/rsa/rsa.pub # 公钥地址
    cookieName: LY_TOKEN
  filter: #过滤鉴权放行白名单
    allowPaths:
    - /api/auth
    - /api/search
    - /api/user/register
    - /api/user/check
    - /api/user/code
    - /api/item #这个微服务是暂时的，生产时有些是不能放的