server:
  port: 8081
spring:
  application:
    name: item-service
  datasource:
    url: jdbc:mysql://localhost:3306/yun6?serverTimezone=UTC
    username: root
    password: luozhong168168
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka